export const TEXT_VERTICES_PER_QUAD = 6
export const TEXT_FLOATS_PER_ORIGIN = 3
export const TEXT_FLOATS_PER_POSITION = 2
export const TEXT_FLOATS_PER_UV = 2
export const TEXT_FLOATS_PER_VERTEX = TEXT_FLOATS_PER_POSITION + TEXT_FLOATS_PER_ORIGIN + TEXT_FLOATS_PER_UV
